services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "k#0XA08g)%Rt_1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  printingapi:
    build:
      context: .
      dockerfile: PrintingApi/Dockerfile
    container_name: printing_api
    ports:
      - "5681:8081"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=10.35.91.123,1433;Database=PrintingDB;User=sa;Password=k#0XA08g)%Rt_1234;TrustServerCertificate=True;"

volumes:
  sql_data: 